default: &default
  adapter: postgresql
  encoding: unicode
  user: admin
  password: todo_pass_123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #host: db 
  #port: 5432

development:
  <<: *default
  database: todo_development

test:
  <<: *default
  database: todo_test

production:
  <<: *default
  database: todo_prod
