version: '3'
services:
  db:
    image: postgres:14.2
    container_name: myapp-postgres-14.2
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: ${POSTGRES_DB_DEVELOPMENT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: myapp-redis
    ports:
      - "6379:6379"

  sidekiq:
    build: .
    command: bundle exec sidekiq --verbose
    volumes:
      - .:/app
    environment:
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - redis

volumes:
  postgres_data:
